# Generated by Django 5.2.12 on 2026-04-09 07:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship')], max_length=20)),
                ('category', models.CharField(choices=[('engineering', 'Engineering & Technology'), ('design', 'Design & Creative'), ('marketing', 'Marketing & Communications'), ('sales', 'Sales & Business Development'), ('finance', 'Finance & Accounting'), ('hr', 'Human Resources'), ('customer_service', 'Customer Service & Support'), ('operations', 'Operations & Logistics'), ('healthcare', 'Healthcare & Medical'), ('education', 'Education & Training'), ('legal', 'Legal'), ('data', 'Data & Analytics'), ('product', 'Product Management'), ('admin', 'Administrative & Clerical'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job_board.employerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
